export default [
  {
    townShip: "梅里镇",
    agriculturalClassification: '养殖业',
    chargePerson: "",
    companyAddress: "梅李镇赵市村",
    companyHonor: "",
    companyId: "1",
    companyName: "稻米专业合作社",
    companyType: "1",
    contactMobile: "",
    contactPerson: "程晓刚",
    contactWay: "0512-52380296",
    createTime: "",
    createUserId: "",
    creditCode: "",
    doSupervision: "",
    landSource: "",
    plantArea: "",
    productInfo: {
      data_0_0: '',
      data_0_1: '',
      data_0_2: '',
      data_0_3: '',
      data_1_0: '',
      data_1_1: '',
      data_1_2: '',
      data_2_0: '',
      data_2_1: '',
      data_3_0: '',
      data_3_1: '',
    },
    qualityStandardId: "",
    remarks: "",
    townId: "",
    updateTime: "",
    updateUserId: ""
  }
]