let privilegeList1 = [{
    id: "aquatic",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "aquatic",
    privilegeName: "水产站",
    path: null,
    type: 1,
    parentId: null,
    seq: 57,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "companyBusiness",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "companyBusiness",
    privilegeName: "经营主体",
    path: null,
    type: 1,
    parentId: null,
    seq: 26,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "deletecompanyBusiness",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "deletecompanyBusiness",
    privilegeName: "经营主体/经营产品/删除",
    path: null,
    type: 2,
    parentId: "companyBusiness",
    seq: 31,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "detailsCompanyBusiness",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "detailsCompanyBusiness",
    privilegeName: "经营主体/企业详情",
    path: null,
    type: 2,
    parentId: "companyBusiness",
    seq: 28,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "productBusiness",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "productBusiness",
    privilegeName: "经营主体/经营产品",
    path: null,
    type: 2,
    parentId: "companyBusiness",
    seq: 29,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "searchcompanyBusiness",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "searchcompanyBusiness",
    privilegeName: "经营主体/搜索",
    path: null,
    type: 2,
    parentId: "companyBusiness",
    seq: 27,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "corporateCreditFile",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "corporateCreditFile",
    privilegeName: "企业信用档案",
    path: null,
    type: 1,
    parentId: null,
    seq: 39,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "searchcorporateCreditFile",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "searchcorporateCreditFile",
    privilegeName: "企业信用档案/导入",
    path: null,
    type: 2,
    parentId: "corporateCreditFile",
    seq: 40,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "creditRating",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "creditRating",
    privilegeName: "信用评级",
    path: null,
    type: 1,
    parentId: null,
    seq: 41,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "detailCreditRating",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "detailCreditRating",
    privilegeName: "信用评级/查看",
    path: null,
    type: 2,
    parentId: "creditRating",
    seq: 44,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "searchcreditRating",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "searchcreditRating",
    privilegeName: "信用评级/搜索",
    path: null,
    type: 2,
    parentId: "creditRating",
    seq: 42,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "synccreditRating",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "synccreditRating",
    privilegeName: "信用评级/同步数据",
    path: null,
    type: 2,
    parentId: "creditRating",
    seq: 43,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "disabilityCheck",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "disabilityCheck",
    privilegeName: "农残检测",
    path: null,
    type: 1,
    parentId: null,
    seq: 32,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "searchdisabilityCheck",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "searchdisabilityCheck",
    privilegeName: "农残检测/搜索",
    path: null,
    type: 2,
    parentId: "disabilityCheck",
    seq: 33,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "greenProducts",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "greenProducts",
    privilegeName: "绿色优质产品",
    path: null,
    type: 1,
    parentId: null,
    seq: 69,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "internalMessage",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "internalMessage",
    privilegeName: "站内消息",
    path: null,
    type: 1,
    parentId: null,
    seq: 74,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "notice",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "notice",
    privilegeName: "通知管理",
    path: null,
    type: 1,
    parentId: null,
    seq: 54,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "smsNotice",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "smsNotice",
    privilegeName: "通知管理/短信通知",
    path: null,
    type: 2,
    parentId: "notice",
    seq: 55,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "addProductionStandard",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "addProductionStandard",
    privilegeName: "生产标准/添加",
    path: null,
    type: 2,
    parentId: "productionStandard",
    seq: 67,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "productionStandard",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "productionStandard",
    privilegeName: "生产标准",
    path: null,
    type: 1,
    parentId: null,
    seq: 66,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "detailsRegulatoryObject",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "detailsRegulatoryObject",
    privilegeName: "生产主体/详情",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 24,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "inventoryDynamics",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "inventoryDynamics",
    privilegeName: "生产主体/产品/库存动态",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 17,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "mainProduct",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "mainProduct",
    privilegeName: "生产主体/产品",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 6,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "productBatch",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "productBatch",
    privilegeName: "生产主体/产品/产品批次",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 8,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "productionSubject",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "productionSubject",
    privilegeName: "生产主体",
    path: null,
    type: 1,
    parentId: null,
    seq: 1,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "searchRegulatoryObject",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "searchRegulatoryObject",
    privilegeName: "生产主体/搜索",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 25,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "thirdPartySamplingRecord",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "thirdPartySamplingRecord",
    privilegeName: "生产主体/产品/第三方抽检记录",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 13,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "viewWarehouse",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "viewWarehouse",
    privilegeName: "生产主体/仓储环境/查看",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 21,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "warehouseEnv",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "warehouseEnv",
    privilegeName: "生产主体/仓储环境",
    path: null,
    type: 2,
    parentId: "productionSubject",
    seq: 19,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "redBlackList",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "redBlackList",
    privilegeName: "红黑名单",
    path: null,
    type: 1,
    parentId: null,
    seq: 46,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "regulatoryRecord",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "regulatoryRecord",
    privilegeName: "监管记录",
    path: null,
    type: 1,
    parentId: null,
    seq: 36,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "searchregulatoryRecord",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "searchregulatoryRecord",
    privilegeName: "监管记录/搜索",
    path: null,
    type: 2,
    parentId: "regulatoryRecord",
    seq: 38,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "sampleCheckMain",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "sampleCheckMain",
    privilegeName: "例行抽样",
    path: null,
    type: 1,
    parentId: null,
    seq: 65,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "seed",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "seed",
    privilegeName: "种子管理",
    path: null,
    type: 1,
    parentId: null,
    seq: 58,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "addShareFiles",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "addShareFiles",
    privilegeName: "共享文件/新建文件夹",
    path: null,
    type: 2,
    parentId: "shareFiles",
    seq: 71,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "deleteshareFiles",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "deleteshareFiles",
    privilegeName: "共享文件/删除",
    path: null,
    type: 2,
    parentId: "shareFiles",
    seq: 73,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "editShareFiles",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "editShareFiles",
    privilegeName: "共享文件/修改",
    path: null,
    type: 2,
    parentId: "shareFiles",
    seq: 72,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "shareFiles",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "shareFiles",
    privilegeName: "共享文件",
    path: null,
    type: 1,
    parentId: null,
    seq: 70,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "specialCategory",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "specialCategory",
    privilegeName: "专项",
    path: null,
    type: 1,
    parentId: null,
    seq: 68,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "statisticsCredit",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "statisticsCredit",
    privilegeName: "诚信系统看板",
    path: null,
    type: 1,
    parentId: null,
    seq: 75,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "statisticsFarmers",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "statisticsFarmers",
    privilegeName: "农残检测看板",
    path: null,
    type: 1,
    parentId: null,
    seq: 79,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "statisticsSupervision",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "statisticsSupervision",
    privilegeName: "监管记录看板",
    path: null,
    type: 1,
    parentId: null,
    seq: 76,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "statisticsTracingCompany",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "statisticsTracingCompany",
    privilegeName: "溯源企业看板",
    path: null,
    type: 1,
    parentId: null,
    seq: 78,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "statisticsTracing",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "statisticsTracing",
    privilegeName: "溯源记录看板",
    path: null,
    type: 1,
    parentId: null,
    seq: 77,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "manageSupervisionGrid",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "manageSupervisionGrid",
    privilegeName: "监管网格/管理",
    path: null,
    type: 2,
    parentId: "supervisionGrid",
    seq: 48,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "supervisionGrid",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "supervisionGrid",
    privilegeName: "监管网格",
    path: null,
    type: 1,
    parentId: null,
    seq: 47,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "threeProductsCertification",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "threeProductsCertification",
    privilegeName: "三品一标认证",
    path: null,
    type: 1,
    parentId: null,
    seq: 63,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "trainingFunds",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "trainingFunds",
    privilegeName: "培训经费管理",
    path: null,
    type: 1,
    parentId: null,
    seq: 60,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "addWorkTask",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "addWorkTask",
    privilegeName: "工作任务/添加",
    path: null,
    type: 2,
    parentId: "workTask",
    seq: 50,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "detailWorkTaskReport",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "detailWorkTaskReport",
    privilegeName: "工作任务/查看任务进度",
    path: null,
    type: 2,
    parentId: "workTask",
    seq: 53,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "editWorkTask",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "editWorkTask",
    privilegeName: "工作任务/修改",
    path: null,
    type: 2,
    parentId: "workTask",
    seq: 52,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  },
  {
    id: "workTask",
    createBy: null,
    createTime: null,
    updateBy: null,
    updateTime: null,
    delFlag: 0,
    status: 0,
    privilegeCode: "workTask",
    privilegeName: "工作任务",
    path: null,
    type: 1,
    parentId: null,
    seq: 49,
    icon: null,
    appId: "zhsnqualitysupervision",
    flag: null,
    children: null
  }
];
let privilegeList2 = [
    {
        "id": "aquatic",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "aquatic",
        "privilegeName": "水产站",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 57,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "companyBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "companyBusiness",
        "privilegeName": "经营主体",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 26,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "deletecompanyBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "deletecompanyBusiness",
        "privilegeName": "经营主体/经营产品/删除",
        "path": null,
        "type": 2,
        "parentId": "companyBusiness",
        "seq": 31,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "detailsCompanyBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "detailsCompanyBusiness",
        "privilegeName": "经营主体/企业详情",
        "path": null,
        "type": 2,
        "parentId": "companyBusiness",
        "seq": 28,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productBusiness",
        "privilegeName": "经营主体/经营产品",
        "path": null,
        "type": 2,
        "parentId": "companyBusiness",
        "seq": 29,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "searchcompanyBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "searchcompanyBusiness",
        "privilegeName": "经营主体/搜索",
        "path": null,
        "type": 2,
        "parentId": "companyBusiness",
        "seq": 27,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "corporateCreditFile",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "corporateCreditFile",
        "privilegeName": "企业信用档案",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 39,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "searchcorporateCreditFile",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "searchcorporateCreditFile",
        "privilegeName": "企业信用档案/导入",
        "path": null,
        "type": 2,
        "parentId": "corporateCreditFile",
        "seq": 40,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "creditRating",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "creditRating",
        "privilegeName": "信用评级",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 41,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "editCreditRating",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "editCreditRating",
        "privilegeName": "信用评级/修改",
        "path": null,
        "type": 2,
        "parentId": "creditRating",
        "seq": 45,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "searchcreditRating",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "searchcreditRating",
        "privilegeName": "信用评级/搜索",
        "path": null,
        "type": 2,
        "parentId": "creditRating",
        "seq": 42,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "synccreditRating",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "synccreditRating",
        "privilegeName": "信用评级/同步数据",
        "path": null,
        "type": 2,
        "parentId": "creditRating",
        "seq": 43,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "disabilityCheck",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "disabilityCheck",
        "privilegeName": "农残检测",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 32,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "searchdisabilityCheck",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "searchdisabilityCheck",
        "privilegeName": "农残检测/搜索",
        "path": null,
        "type": 2,
        "parentId": "disabilityCheck",
        "seq": 33,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "greenProducts",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "greenProducts",
        "privilegeName": "绿色优质产品",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 69,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "internalMessage",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "internalMessage",
        "privilegeName": "站内消息",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 74,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "editNotice",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "editNotice",
        "privilegeName": "通知管理/修改",
        "path": null,
        "type": 2,
        "parentId": "notice",
        "seq": 56,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "notice",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "notice",
        "privilegeName": "通知管理",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 54,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productionStandard",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productionStandard",
        "privilegeName": "生产标准",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 66,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addRegulatoryObject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addRegulatoryObject",
        "privilegeName": "生产主体/添加",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 2,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "detailsRegulatoryObject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "detailsRegulatoryObject",
        "privilegeName": "生产主体/详情",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 24,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "editRegulatoryObject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "editRegulatoryObject",
        "privilegeName": "生产主体/修改",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 3,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "inventoryDynamics",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "inventoryDynamics",
        "privilegeName": "生产主体/产品/库存动态",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 17,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "mainProduct",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "mainProduct",
        "privilegeName": "生产主体/产品",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 6,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productBatch",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productBatch",
        "privilegeName": "生产主体/产品/产品批次",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 8,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productionSubject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productionSubject",
        "privilegeName": "生产主体",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 1,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "searchproductionSubject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "searchproductionSubject",
        "privilegeName": "生产主体/修改/校验",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 4,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "searchRegulatoryObject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "searchRegulatoryObject",
        "privilegeName": "生产主体/搜索",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 25,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "thirdPartySamplingRecord",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "thirdPartySamplingRecord",
        "privilegeName": "生产主体/产品/第三方抽检记录",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 13,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "viewWarehouse",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "viewWarehouse",
        "privilegeName": "生产主体/仓储环境/查看",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 21,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "warehouseEnv",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "warehouseEnv",
        "privilegeName": "生产主体/仓储环境",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 19,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "redBlackList",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "redBlackList",
        "privilegeName": "红黑名单",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 46,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addRegulatoryRecord",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addRegulatoryRecord",
        "privilegeName": "监管记录/添加",
        "path": null,
        "type": 2,
        "parentId": "regulatoryRecord",
        "seq": 37,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "regulatoryRecord",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "regulatoryRecord",
        "privilegeName": "监管记录",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 36,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "sampleCheckMain",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "sampleCheckMain",
        "privilegeName": "例行抽样",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 65,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "seed",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "seed",
        "privilegeName": "种子管理",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 58,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "uploadSeed",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "uploadSeed",
        "privilegeName": "种子管理/上传种子",
        "path": null,
        "type": 2,
        "parentId": "seed",
        "seq": 59,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "shareFiles",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "shareFiles",
        "privilegeName": "共享文件",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 70,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "specialCategory",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "specialCategory",
        "privilegeName": "专项",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 68,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "statisticsCredit",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "statisticsCredit",
        "privilegeName": "诚信系统看板",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 75,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "statisticsFarmers",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "statisticsFarmers",
        "privilegeName": "农残检测看板",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 79,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "statisticsSupervision",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "statisticsSupervision",
        "privilegeName": "监管记录看板",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 76,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "statisticsTracingCompany",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "statisticsTracingCompany",
        "privilegeName": "溯源企业看板",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 78,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "statisticsTracing",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "statisticsTracing",
        "privilegeName": "溯源记录看板",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 77,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "manageSupervisionGrid",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "manageSupervisionGrid",
        "privilegeName": "监管网格/管理",
        "path": null,
        "type": 2,
        "parentId": "supervisionGrid",
        "seq": 48,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "supervisionGrid",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "supervisionGrid",
        "privilegeName": "监管网格",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 47,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "threeProductsCertification",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "threeProductsCertification",
        "privilegeName": "三品一标认证",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 63,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addTrainingFunds",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addTrainingFunds",
        "privilegeName": "培训经费管理/添加",
        "path": null,
        "type": 2,
        "parentId": "trainingFunds",
        "seq": 61,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "trainingFunds",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "trainingFunds",
        "privilegeName": "培训经费管理",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 60,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addWorkTaskReport",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addWorkTaskReport",
        "privilegeName": "工作任务/查看任务",
        "path": null,
        "type": 2,
        "parentId": "workTask",
        "seq": 51,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "workTask",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "workTask",
        "privilegeName": "工作任务",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 49,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    }
];
let privilegeList3 = [
    {
        "id": "addProductBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addProductBusiness",
        "privilegeName": "经营主体/经营产品/添加",
        "path": null,
        "type": 2,
        "parentId": "companyBusiness",
        "seq": 30,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "companyBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "companyBusiness",
        "privilegeName": "经营主体",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 26,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "deletecompanyBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "deletecompanyBusiness",
        "privilegeName": "经营主体/经营产品/删除",
        "path": null,
        "type": 2,
        "parentId": "companyBusiness",
        "seq": 31,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productBusiness",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productBusiness",
        "privilegeName": "经营主体/经营产品",
        "path": null,
        "type": 2,
        "parentId": "companyBusiness",
        "seq": 29,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "corporateCreditFile",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "corporateCreditFile",
        "privilegeName": "企业信用档案",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 39,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "creditRating",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "creditRating",
        "privilegeName": "信用评级",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 41,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "209518168111058944",
        "createBy": null,
        "createTime": null,
        "updateBy": "199091706153406464",
        "updateTime": "2019-11-20 18:04",
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "dataDirectory",
        "privilegeName": "数据目录",
        "path": "",
        "type": 1,
        "parentId": "",
        "seq": null,
        "icon": "",
        "appId": "209510866792484864",
        "flag": null,
        "children": null
    },
    {
        "id": "209518443836215296",
        "createBy": null,
        "createTime": null,
        "updateBy": "199091706153406464",
        "updateTime": "2019-11-20 18:04",
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "viewDataDirectory",
        "privilegeName": "查看",
        "path": "",
        "type": 2,
        "parentId": "209518168111058944",
        "seq": null,
        "icon": "",
        "appId": "209510866792484864",
        "flag": null,
        "children": null
    },
    {
        "id": "disabilityCheck",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "disabilityCheck",
        "privilegeName": "农残检测",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 32,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "inputManagement",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "inputManagement",
        "privilegeName": "投入品管理",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 62,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "jobDefinition",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "jobDefinition",
        "privilegeName": "作业定义",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 34,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productionRecord",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productionRecord",
        "privilegeName": "生产记录",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 35,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productionStandard",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productionStandard",
        "privilegeName": "生产标准",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 66,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addInventoryDynamics",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addInventoryDynamics",
        "privilegeName": "生产主体/产品/库存动态/添加",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 18,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addMainProduct",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addMainProduct",
        "privilegeName": "生产主体/产品/添加",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 7,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addProductBatch",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addProductBatch",
        "privilegeName": "生产主体/产品/产品批次/添加",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 9,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addThirdPartySampling",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addThirdPartySampling",
        "privilegeName": "生产主体/产品/第三方抽检记录/添加",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 14,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "addWarehouse",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "addWarehouse",
        "privilegeName": "生产主体/仓储环境/添加",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 20,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "deleteproductionSubject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "deleteproductionSubject",
        "privilegeName": "生产主体/修改/删除",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 5,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "deleteWarehouse",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "deleteWarehouse",
        "privilegeName": "生产主体/仓储环境/删除",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 23,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "detailsWarehouse",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "detailsWarehouse",
        "privilegeName": "生产主体/仓储环境/修改",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 22,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "editMainProduct",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "editMainProduct",
        "privilegeName": "生产主体/产品/修改",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 12,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "editRegulatoryObject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "editRegulatoryObject",
        "privilegeName": "生产主体/修改",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 3,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "inventoryDynamics",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "inventoryDynamics",
        "privilegeName": "生产主体/产品/库存动态",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 17,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "mainProduct",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "mainProduct",
        "privilegeName": "生产主体/产品",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 6,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "processDefinition",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "processDefinition",
        "privilegeName": "生产主体/产品/作业定义",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 10,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productBatch",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productBatch",
        "privilegeName": "生产主体/产品/产品批次",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 8,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productionSubject",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productionSubject",
        "privilegeName": "生产主体",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 1,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productProperty",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productProperty",
        "privilegeName": "生产主体/产品/属性管理",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 15,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "productVariety",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "productVariety",
        "privilegeName": "生产主体/产品/品种定义",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 11,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "thirdPartySamplingRecord",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "thirdPartySamplingRecord",
        "privilegeName": "生产主体/产品/第三方抽检记录",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 13,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "warehouseEnv",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "warehouseEnv",
        "privilegeName": "生产主体/仓储环境",
        "path": null,
        "type": 2,
        "parentId": "productionSubject",
        "seq": 19,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "redBlackList",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "redBlackList",
        "privilegeName": "红黑名单",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 46,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "209518074414501888",
        "createBy": null,
        "createTime": null,
        "updateBy": "199091706153406464",
        "updateTime": "2019-11-20 18:05",
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "resourceStatistics",
        "privilegeName": "资源统计",
        "path": "",
        "type": 1,
        "parentId": "",
        "seq": null,
        "icon": "",
        "appId": "209510866792484864",
        "flag": null,
        "children": null
    },
    {
        "id": "209518307831713792",
        "createBy": null,
        "createTime": null,
        "updateBy": "199091706153406464",
        "updateTime": "2019-11-20 18:04",
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "viewResourceStatistics",
        "privilegeName": "查看",
        "path": "",
        "type": 2,
        "parentId": "209518074414501888",
        "seq": null,
        "icon": "",
        "appId": "209510866792484864",
        "flag": null,
        "children": null
    },
    {
        "id": "sampleCheckMain",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "sampleCheckMain",
        "privilegeName": "例行抽样",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 65,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    },
    {
        "id": "tracingLabelManagement",
        "createBy": null,
        "createTime": null,
        "updateBy": null,
        "updateTime": null,
        "delFlag": 0,
        "status": 0,
        "privilegeCode": "tracingLabelManagement",
        "privilegeName": "溯源标签管理",
        "path": null,
        "type": 1,
        "parentId": null,
        "seq": 64,
        "icon": null,
        "appId": "zhsnqualitysupervision",
        "flag": null,
        "children": null
    }
];
export {privilegeList1, privilegeList2, privilegeList3};