export default [
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "2",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "3",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "4",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "4",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
  {
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },{
    id: "1",
    companyname: "稻米专业合作社",
    productname: "稻米合作社",
    productcategory: "专业合作社",
    authType: "稻米专业合",
  },
]